leftnav:
- identifier: 6cc61656-d92d-7ba5-bc26-60f07f8d24c8
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 78cb7749-2b45-3905-5aca-aacacf27eea7
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 20
- identifier: 412120c3-d837-bae9-2e73-08a2d78e8810
  name: Lecture Summaries
  pageRef: /pages/lecture-summaries
  weight: 30
- identifier: 7e163d7b-0bbf-2a37-2c6c-f5874f31469c
  name: Readings
  pageRef: /pages/readings
  weight: 40
- identifier: e3e43ca7-1f9f-80b3-24f0-8591f30a22eb
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
